services:
  - type: web
    name: temple-token-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: redirect
        source: /index.html
        destination: /
      - type: rewrite
        source: /*
        destination: /index.html
